# Generated by Django 6.0.4 on 2026-04-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redesign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='scene_type',
            field=models.CharField(default='interior', max_length=20),
        ),
    ]
