# Generated by Django 6.0.4 on 2026-04-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redesign', '0002_designrequest_scene_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='request_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
